<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ADS107-AHQ" failures="1" tests="7" name="tests.Profile.AddPersonalinfo" time="255.996" errors="0" timestamp="2020-11-02T10:19:30 EET" skipped="0">
  <testcase classname="tests.Profile.AddPersonalinfo" name="personalinfo" time="15.423"/>
  <system-out/>
  <testcase classname="tests.Profile.AddPersonalinfo" name="addGender" time="53.478"/>
  <system-out/>
  <testcase classname="tests.Profile.AddPersonalinfo" name="addBloodType" time="35.679"/>
  <system-out/>
  <testcase classname="tests.Profile.AddPersonalinfo" name="CheckEmail" time="15.533"/>
  <system-out/>
  <testcase classname="tests.Profile.AddPersonalinfo" name="addMaritalStatus" time="42.321"/>
  <system-out/>
  <testcase classname="tests.Profile.AddPersonalinfo" name="addNumberofChildren" time="53.448">
    <failure message="The following asserts failed:
	Data displayed in DDl Not Match with data Saved in DB expected [0] but found [none]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Data displayed in DDl Not Match with data Saved in DB expected [0] but found [none]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at tests.Profile.AddPersonalinfo.addNumberofChildren(AddPersonalinfo.java:126)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addNumberofChildren -->
  <system-out/>
  <testcase classname="tests.Profile.AddPersonalinfo" name="addEducation" time="40.114"/>
  <system-out/>
</testsuite> <!-- tests.Profile.AddPersonalinfo -->
